name: Rust

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:

  compile:
    runs-on: ubuntu-latest
    if: ${{ github.ref_protected }}
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - uses: actions/checkout@v2
    - name: Compile
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    if: ${{ github.ref_protected }}
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
